on:
  push:
   tags:
     - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    name: ExUnit - Elixir ${{matrix.elixir}} (${{matrix.otp}})
    strategy:
      matrix:
        otp: ['25']
        elixir: ['1.14']
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix test --color

  credo:
    runs-on: ubuntu-latest
    name: Credo - Elixir ${{matrix.elixir}} (${{matrix.otp}})
    strategy:
      matrix:
        otp: ['25']
        elixir: ['1.14']
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix credo

  coveralls:
    runs-on: ubuntu-latest
    name: Codecov report
    needs:
      - test
      - credo
    env:
      MIX_ENV: test
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-25-1.14-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)

  publish:
    name: "Publish to hex.pm"
    needs: 
      - test
      - credo
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Publish to Hex.pm
        uses: HypeRate/action-publish-hex@v2
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
