on:
  push:
   tags:
     - "v*"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  publish:
    name: "Publish to hex.pm"
    needs: 
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Publish to Hex.pm
        uses: HypeRate/action-publish-hex@v2
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
