on: [push, pull_request]

name: Quality assurance

jobs:
  test:
    runs-on: ubuntu-latest
    name: ExUnit - Elixir ${{matrix.elixir}} (${{matrix.otp}})
    strategy:
      matrix:
        otp: ['25']
        elixir: ['1.14']
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix test --color
      - run: mix coveralls

  credo:
    needs: "test"
    runs-on: ubuntu-latest
    name: Credo - Elixir ${{matrix.elixir}} (${{matrix.otp}})
    strategy:
      matrix:
        otp: ['25']
        elixir: ['1.14']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix credo

  coveralls:
    runs-on: ubuntu-latest
    name: Coveralls report
    needs: "credo"
    if: github.ref == 'refs/heads/master'
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-25-1.14-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix coveralls.github
